apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: "my-volume"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv